Добавляет разметку в HTML
htmlacademy-adaptive/2188619-sedona-27 pull request #2
Opened 2022-12-06 14:30 UTC by Aleksey177

2022-12-06 20:10 UTC, Kartaviy-arteom requested changes

2022-12-06 20:10 UTC, Kartaviy-arteom commented on source/index.html
> +      <header class="hero-block__header">
здесь хедер не нужен

2022-12-06 20:10 UTC, Kartaviy-arteom commented on source/index.html
> +          <p class="hero-block__intro">Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</p>
"Рассмотрим 5 причин" и сами причины в одной секции

2022-12-06 20:10 UTC, Kartaviy-arteom commented on source/index.html
> +          <p class="advantages__item-number">-№1-</p>
лучше спан, для одного слова это перебор

2022-12-06 20:10 UTC, Kartaviy-arteom commented on source/index.html
> +        </div>
я бы собрал их в одну причину, т.е вложил бы списком в первую причину. У тебя их всего 5 шт

2022-12-06 20:10 UTC, Kartaviy-arteom commented on source/index.html
> +            <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy"></a>
нужно добавить пояснения для этих ссылок, что-то типо <span class="visually-hidden">Ютуб</span>

2022-12-06 20:10 UTC, Kartaviy-arteom commented on source/index.html
> +  </footer>
А страницу формы и каталога?

2022-12-08 12:52 UTC, Aleksey177 commented on source/index.html
> +      <header class="hero-block__header">
Удалил хедер, оставил только обёртку

2022-12-08 12:55 UTC, Aleksey177 commented on source/index.html
> +          <p class="hero-block__intro">Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</p>
Это понятно, забыл удалить закрывающий тег, исправил

2022-12-08 12:57 UTC, Aleksey177 commented on source/index.html
> +          <p class="advantages__item-number">-№1-</p>
заменил на спан

2022-12-08 13:02 UTC, Aleksey177 commented on source/index.html
> +            <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy"></a>
Добавил скрытый спан

2022-12-08 17:28 UTC, Aleksey177 commented on source/index.html
> +        </div>
исправил

2022-12-09 16:18 UTC, Kartaviy-arteom requested changes

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/form.html
> +                <label class="feedback__label" for="Имя">Имя<sup>*</sup>:</label>
невалидный атрибут

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/form.html
> +                <label class="feedback__label" for="Фамилия">Фамилия<sup>*</sup>:</label>
невалидный атрибут

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/form.html
> +                <label class="feedback__label" for="Отчество">Отчество:</label>
невалидный атрибут

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/form.html
> +                <label class="feedback__label" for="Контактный телефон">Контактный телефон<sup>*</sup>:</label>
невалидный атрибут

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/form.html
> +                <label class="feedback__label" for="Электронная почта">Электронная почта<sup>*</sup>:</label>
невалидный атрибут

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/form.html
> +            <label class="visually-hidden" for="Опишите свои эмоции">Опишите свои эмоции</label>
невалидный атрибут

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/index.html
> +<html class="page" lang="ru">
эти классы не нужны

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/index.html
> +<body class="page__body">
тоже не к чему

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/index.html
> +      <img src="" width="185" height="96" alt="Cedona."></a>
Sedona

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/index.html
> +          <ul class="card-bonus">
можно bonus-list

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/catalog.html
> +          <h3 class="gallery__item-title">Местная растительность</h3>
форматирование кода, во всех документах

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/form.html
> +                <input class="feedback__field" type="text" placeholder="Пётр">
поля с * обязательные

2022-12-09 16:18 UTC, Kartaviy-arteom commented on source/form.html
> +            <input class="feedback__field feedback__field-emotions" type="text" name="Опишите свои эмоции"
это textarea

2022-12-12 18:39 UTC, Aleksey177 commented on source/index.html
> +      <img src="" width="185" height="96" alt="Cedona."></a>
исправил

2022-12-12 18:42 UTC, Aleksey177 commented on source/index.html
> +          <ul class="card-bonus">
исправил

2022-12-12 18:50 UTC, Aleksey177 commented on source/catalog.html
> +          <h3 class="gallery__item-title">Местная растительность</h3>
поправил

2022-12-12 19:04 UTC, Aleksey177 commented on source/form.html
> +            <input class="feedback__field feedback__field-emotions" type="text" name="Опишите свои эмоции"
заменил на textarea

2022-12-12 19:04 UTC, Aleksey177 commented on source/form.html
> +                <label class="feedback__label" for="Имя">Имя<sup>*</sup>:</label>
исправил

2022-12-12 19:05 UTC, Aleksey177 commented on source/form.html
> +                <label class="feedback__label" for="Фамилия">Фамилия<sup>*</sup>:</label>
исправил

2022-12-12 19:05 UTC, Aleksey177 commented on source/form.html
> +                <label class="feedback__label" for="Отчество">Отчество:</label>
исправил

2022-12-12 19:05 UTC, Aleksey177 commented on source/form.html
> +                <label class="feedback__label" for="Контактный телефон">Контактный телефон<sup>*</sup>:</label>
исправил

2022-12-12 19:05 UTC, Aleksey177 commented on source/form.html
> +                <label class="feedback__label" for="Электронная почта">Электронная почта<sup>*</sup>:</label>
исправил

2022-12-12 19:19 UTC, Aleksey177 commented on source/form.html
> +            <label class="visually-hidden" for="Опишите свои эмоции">Опишите свои эмоции</label>
исправил

2022-12-12 19:20 UTC, Aleksey177 commented on source/index.html
> +<html class="page" lang="ru">
пока оставлю, если что потом удалю

2022-12-12 19:20 UTC, Aleksey177 commented on source/index.html
> +<body class="page__body">
пока оставлю, если что потом удалю

2022-12-13 19:21 UTC, Kartaviy-arteom approved these changes

2022-12-13 19:21 UTC, Kartaviy-arteom commented on source/index.html
> +<html class="page" lang="ru">
а это было в демонстрации. Просто это избыточно

2022-12-13 19:21 UTC, Kartaviy-arteom commented on source/index.html
> +            <li class="bonus__item card__inner card__housing">
это не по бэму. Элементы без блока

2022-12-13 19:21 UTC, merged