Добавляет декоративные элементы
htmlacademy-adaptive/2188619-sedona-27 pull request #5
Opened 2023-01-16 20:12 UTC by Aleksey177

2023-01-18 16:49 UTC, Kartaviy-arteom requested changes
Project check / Check (pull_request)  - тут есть ошибки, автопроверки при пулреквесте их тоже нужно править

2023-01-18 16:49 UTC, Kartaviy-arteom commented on source/less/blocks/catalog.less
> +  background-image: url("../../img/icons/icon-like-grey.svg");
Зачем тебе несколько иконок, она же монотонная?

2023-01-18 16:49 UTC, Kartaviy-arteom commented on source/catalog.html
> +  <script src="./js/script.js"></script>
В каталоге есть невалидная разметка, не закрыт тег. Это создаст тебе проблем, так же на других страницах. Нужно сначала починить разметку, потом стили подправить. так проблема в каталоге еще из-за catalog__item-img
Нужно исправить БЭМ https://yoksel.github.io/html-tree/

2023-01-18 16:49 UTC, Kartaviy-arteom commented on source/form.html
> +  <script src="./js/script.js"></script>
тоже бэм

2023-01-18 16:49 UTC, Kartaviy-arteom commented on source/index.html
> +  <script src="./js/script.js"></script>
тоже бэм, не конкретно на этой строке. По всему файлу

2023-01-18 16:49 UTC, Kartaviy-arteom commented on source/less/mixing.less
> +  font-family: "PT Sans", "Arial", sans-serif;
в названии файла ошибка. mixin

2023-01-18 16:49 UTC, Kartaviy-arteom commented on source/js/script.js
> +});
с отключенным js меню не открывается.

2023-01-18 16:49 UTC, Kartaviy-arteom commented on source/less/blocks/feedback.less
> +    height: 3px;
у тебя в этом блоке кнопка уползает

2023-01-20 13:25 UTC, Aleksey177 commented on source/catalog.html
> +  <script src="./js/script.js"></script>
Исправил

2023-01-20 13:55 UTC, Aleksey177 commented on source/form.html
> +  <script src="./js/script.js"></script>
исправил

2023-01-20 14:03 UTC, Aleksey177 commented on source/index.html
> +  <script src="./js/script.js"></script>
исправил

2023-01-20 14:04 UTC, Aleksey177 commented on source/less/mixing.less
> +  font-family: "PT Sans", "Arial", sans-serif;
переименовал

2023-01-20 14:42 UTC, Aleksey177 commented on source/less/blocks/feedback.less
> +    height: 3px;
Исправил

2023-01-22 18:42 UTC, Kartaviy-arteom approved these changes
1. подправить манифест
2. исправить меню
3. подправить пиксель пефект
4. на главеной нет полосок, подчеркивающие карточки
5. невалидная главная, каталог, форма
6. Картинка под картой
7. на страницы формы на мобилке лишние линии, на планшете их наоборот не хватает

2023-01-22 18:42 UTC, Kartaviy-arteom commented on source/manifest.webmanifest
> +    { "src": "img/favicons/apple-icon-180x180.png", "type": "image/png", "sizes": "180x180" }
180*180 ты уже подключил в head
"512x512"  не было

2023-01-22 18:42 UTC, merged